### ISSUE TITLE
Slow motion audio

### ISSUE THREAD

**Issue by jubalh** [chickendude/Natibo#20]
An option to play the audio in a slower tempo might be helpful.

**Comment by chickendude** [comment]
Unfortunately i think this would likely take a bit of work to get it working on older phones, the sentences are played with a MediaPlayer which doesn't (or rather didn't used to) have a way to change playback speed. I think on SDK 23 (Android 6.0) and above it should be possible, so that should still cover a good portion of the userbase (if it ever gets one ;) ). I don't generally use these features as the audio tends to get too distorted to be useful anyway, but we could look into it.

**Comment by RpiDude** [comment]
I second this request, maybe you can use https://github.com/waywardgeek/sonic

**Comment by chickendude** [comment]
@flackbash 's pull request added this for SDK 23 and up. For lower SDK levels i don't think it's really feasible at the moment, if someone else wants to add support for lower SDK levels i'd be more than happy to help out.
