### ISSUE TITLE
Stop timer when stopping audio

### ISSUE THREAD

**Issue by jubalh** [chickendude/Natibo#25]
Currently the timer continues to count down when one presses the pause button.

**Comment by chickendude** [comment]
The timer has a bunch of issues, some of them were hotfixed on the master branch, but i haven't provided an updated apk for that yet as i've been working on the triangulation update. I'll look into this issue again once i've merged the new update onto master to see if it's still an issue. A lot of other bugs have been fixed in the refactorization so far.

**Comment by chickendude** [comment]
Could you check if you can still reproduce this on the latest build? It seems to be working for me now, but in the past i've noticed sometimes the timer works, sometimes it doesn't. If you can still reproduce it, it'd be great if you could provide some steps to reproduce it reliably!

**Comment by jubalh** [comment]
Will try later :)

**Comment by jubalh** [comment]
Although the timer does some strange jumping in general (freezing for a while then displaying the change that actually happened in one go) it now stops when pausing.

Thanks :-)

**Comment by chickendude** [comment]
Yeah, that's because the time remaining gets recounted after each rep, but it takes a while to count the size of each mp3 file (i guess, but that's where the slowdown happens in the code) so i put it in a background thread and update the UI when it's done. I think saving the length in ms of the mp3 file directly as a field in the Sentence object would speed this up a lot, but i haven't tried it out yet.

**Comment by jubalh** [comment]
> I think saving the length in ms of the mp3 file directly as a field in the Sentence object would speed this up a lot, but i haven't tried it out yet.

Sounds like a good idea.

**Comment by chickendude** [comment]
Just implemented this in 71a4a30225af564b0ab8d95f96f8d71c29878923, i added a "timeInMillis" field to the Sentence object which gets filled in when importing a gls file.

**Comment by jubalh** [comment]
There is a bug here.

When I press 'pause' and exactly in the moment the new sentences appear but the audio doenst play yet, and then press 'play' again the time jumps up (+ X minutes, probably depending on the sentence).
