### ISSUE TITLE
link to tool

### ISSUE THREAD

**Issue by jubalh** [chickendude/Natibo#7]
Issue states: `GLS packs (another tool i've been working on to split Glossika GMS/PDF files into individual sentences)`.
Which tools it that, is there a link to it?

**Comment by chickendude** [comment]
The tool is available at https://github.com/chickendude/GlossikaNativeGLS. For the mp3s it's no magic, just using audacity to get the times for each sentence then using a Python mp3 library to split the GMS B files.

The PDFs are a bit more automated, i just put the first/last page of the GMS sentences and use [pdftotext](https://github.com/jalan/pdftotext), unfortunately it's Linux only which is why i initially put the web version up.

**Comment by chickendude** [comment]
I've added a link to the other toolset in the readme :)
